# Generated by Django 3.0.8 on 2021-04-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание новости'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок новости'),
        ),
    ]
