# Generated by Django 3.0.8 on 2021-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210417_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='brief',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Текст письма'),
        ),
        migrations.AddField(
            model_name='participant',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='participant',
            name='file',
            field=models.CharField(blank=True, max_length=100, verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='participant',
            name='nomination',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номинация'),
        ),
        migrations.AddField(
            model_name='participant',
            name='organization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Образовтательная организация'),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='participant',
            name='site',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка на сайт'),
        ),
        migrations.AddField(
            model_name='participant',
            name='video',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка на сайт'),
        ),
    ]
